{% set name = "Flask-SQLAlchemy" %}
{% set version = "2.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b656fbf87c5f24109d859bafa791d29751fabbda2302b606881ae5485b557a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask >=1.0.4
    - sqlalchemy >=1.2

test:
  imports:
    - flask_sqlalchemy

about:
  home: http://github.com/mitsuhiko/flask-sqlalchemy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Adds SQLAlchemy support to your Flask application
  dev_url: https://github.com/mitsuhiko/flask-sqlalchemy
  doc_url: http://flask-sqlalchemy.pocoo.org/{{ version }}/

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
