{% set name = "Flask-SQLAlchemy" %}
{% set version = "3.1.1" %}
{% set file_name = "flask_sqlalchemy" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ file_name }}-{{ version }}.tar.gz
  sha256: e4b68bb881802dda1a7d878b2fc84c06d1ee57fb40b874d3dc97dabfa36b8312

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - flask >=2.2.5
    - sqlalchemy >=1.4.18

test:
  imports:
    - flask_sqlalchemy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets/flask-sqlalchemy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Adds SQLAlchemy support to your Flask application
  description: |
    Flask-SQLAlchemy is an extension for Flask that adds support for SQLAlchemy to your application. 
    It aims to simplify using SQLAlchemy with Flask by providing useful defaults and extra helpers 
    that make it easier to accomplish common tasks.
  dev_url: https://github.com/pallets/flask-sqlalchemy
  doc_url: https://flask-sqlalchemy.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
