{% set name = "Flask-SQLAlchemy" %}
{% set version = "2.0" %}
{% set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "990387d2cff83df7feb40e9d6b286f2679144258480249cbd47b88dc0939e886" %}
{%set build_num = "0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:

  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask >=0.10
    - sqlalchemy >=0.7

test:
  imports:
    - flask_sqlalchemy

about:
  home: http://github.com/mitsuhiko/flask-sqlalchemy
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Adds SQLAlchemy support to your Flask application'
  dev_url: http://github.com/mitsuhiko/flask-sqlalchemy
  doc_url: http://flask-sqlalchemy.pocoo.org/{{ version }}/

extra:
  recipe-maintainers:
    - pmlandwehr
