travis:
  secure:
    BINSTAR_TOKEN: nQ8T9q5lkgmEf1i+J7fXBtHAmhWGZTwJBSc+ABvCoRR3MGUongmmeaB5XpzJNwEfAPfi3G//j3g8qOuIqkOnpgTfCcslYhBaiKYXRWb5RNxVeXXU1eJdrORw/TKq7sRw5g+O8tBgXt5MJHQPLCUTaF9xZoU4jWac18BFUWESu0hZQr3+nlq9x1ggeKl0nF9cjc448oGzNMP33QZZMYXollCf2lHF+VVggB7NeSfpp2YhfW33BlZD/e4/fjuY9+Lro9Q05Q9uLheMToZdu4w8xPpLlgpWXIAsPY21LH3aXf3Cc5vZQvywYnhywm/MkGMGsAAiucvAYByswT80vwhxZns689H1ydGjYDUzPYTQHUhk4xCmyDxcM2JdyDsYgGbys6xwkE9YdTSisZFMT4Tbfc9JqDLMdfHuYEsYhsBRiDvXJ62H41wc+lDntfP522f7MJZZMkSNFc8W/N7Z7Kmwo/5YPAKa8xzVfgO8KxMigg/qdrFgHCeSMWAMxmTCoQpmqxrkjy6tQoAYYF0MdBRvuo0pVBi2V9kQH/GAACpTbuwavE1UbssKMOARoIhiPZJ5MXHKZdpv1aGvXKsetrrwxzYsqpNYPJ35wAksPxAiCi7TCgKR6Brl+qa8zSMP8xLwUR0EvOVeWgVUeAHV7F+S2AM9qAbqrIoyBWpI9hK1v3E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
