travis:
  secure:
    BINSTAR_TOKEN: lppZ5P5YuFXSZVfvOyRLdEJQwYdsIRbRt8OViZtOUg1pC1H5b3VkVroYH38pCrDsUxsxFkAZtW0xcXrr39B/8IVmu4Vogb62yl20tO0HFKnfX072q1G++KITItWgJEYsg/cWJGK5AsZxwVxiKQcd70G2Gk56IzPqB63gSaQe/aDMt6HZL5GqpE9Ul4/iBS6gVQ+gkxFCaywwZ+kH8zfuXes/AvzzwTF88RQO6ecYIBXYvta/mVDZItiwWu2rQIsbMafx7uwTt6sW6l7wgNEAlqUSbA4AegRJBKUizTFsAg7DREr8WQefYwkhkz47yWRSmwfcdcTltQxWFHGQya24Mri4OjuAAg2Yqv0og1Xn272nz+oPIbgNVw2SnRCUVm2Z4+m936hqml1pRfmxappELBom9RryMKW/ug07fqFvS5jwjHFK2z2k/Wdt/GDAykt3Nyyb/+6iS2HmoRUFUuduP0u3zS/nzB2jHGowp0Owr3AiJKHOOj4FNtoOFPOrRKG9GIsO2nRLrRw0eKvf/m6sx6pb9GOxquGqUldsISnRPbg/d1Qpa018bh8k2mBAmG6mWG1iyrSycmBvAYBIwNcO1JASlacQ2EBSZgjJEaEAVz6Jbiv6KbfaxxCs6SNFcLShd3PDcujkKBhZ1NXdtCY7EFlqi96bty8S/v7ORWG7yy8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
