travis:
  secure:
    BINSTAR_TOKEN: co0b1y8u782ghrrYMbiwN8WPFnU3IdS1uE0lT/yNsmPXs04hlf3+XEhUy3TZ8S86BNXs599qr+TSPr79iCh9JVgZe/jC5+5xsi7oINAUURbtXuz5uyP+/pMX6ki2yRLJAuGfjlViVozsHCM3hDcoafpx8r2pIsR8fpvJo5JuYDANf3/1fVUUB1P+MNjgeS7qAGnItcwhioEQDeG6FmUFugxL3un5NueheA3CJQDc2CbB5rQeWQnssuQH8tGswL8yZUiZsUGJmHAErRBqaRf83BMdQHUyUWjOT3oIt/5rw9VkCQ1uGmgD94Xh7Q8YqWujEvuIQuJTsNPO2Wxc/0wyyOJzrkFPquPjaybdDTxMiNZPiOxRXi04MOqhCHnWeD1gJrwtLy4XeG2nWbYpIYkpbSy9zhojlSqu9leZHrTUBk9GjmWEMHF8qCWcAAuQZI1dD5gI2Pz7X7Al1R53iAl8HAUY6qxR/Q+8hImYLKmYADGjPIADzrnjjlzJV1RLnQB49aq/XdpAymSNXS7SlSK/bTWNREU7R7X7lIcVX4YIR5KzlRGG8oe4ZKPDqog2rH+5Nz09HQW7lR+FCxWtB6axlVMEA8FgW9Ew9eOsdJU33CVYYA6TSTzArQPFAOzEpikDD487S5T2D2G+gyGImfbDOKuxcTDwhrWaJt7diEvJkHc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
