travis:
  secure:
    BINSTAR_TOKEN: w+GfSAo7MRVcZpCkdWxvCDh5PO3sSpvLJHUtREyCibfdQcsox3i1PHSs1B9GJ0fzW8mj3+rD5qP34W4ZE2EOg9l9vYgSjCPGSgzKiHCQxHAd0qCbrP1ji7rxzTznwUqn2hj0HHbj/FIzZsd3DKcnaU5gN1iHhQ8+b5XfWEBRAf1UUOxoL3ktE8yVQvo8afRHnGNMFEtwfqcdQ858Y4nK2xTxYwVFTXHOA4oEY1JmUMsMXwaz5xZnGP2peqz3AueTBCnuy75JS6gi3/P3TklM+SH1Q8EV7Fo4Va7jevMfObkhgGj2dI4KOKIgqgcNt/hce25wjdib+rIkPBQs00SzY6bIDyiomoLuZKx57r5YK7mve4GLBOSNsX9syFg+FbAEJ8E/EIxpMJTp1Wo6nQ7T/y3+PNwGwbM83zg9O4pMpwPBOhrs+jK2hd7kVodyHd9zeTbi6v+nNQtj7Cca8trgmAbNuEUMQOoYpGk065eLBtu9VYsvapvUY7uqw8nGTD4C3WsYTBL9sY/XipK0X9s0IzJpilAMW+5RFURdjM2+czqYeDmYa54wjpUKbl9cdwW83irVA2rcSJFgYGtvnOs89eY8fnJLlZJB6pV6oultuZPZKr0RIRiL3m3v5PEn+n/rGQqpgI0Qjs37Z06eg5lHJuDwF8omyuSLRt5/kQdhe9E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
