travis:
  secure:
    BINSTAR_TOKEN: B9Ebz6dzdhnaynwVNTcL0E8RmuhwzK8sjywjAWRzFN7TqGbtQQXEijQNFbVIdoEkUkSNSW2p1UeJhFz1QztTBHPuOmVMqEk9/gMf0E25rYMYu3T6FD0F09cyIOVg9BFkyn+En0ccda2Jm96+RXI44Aa6Zu1O3h7TBu06p6/zLZaxGoWkOyLgxPPgj/fLNtxwUrCJGHbfvAFgOKmDyk31A3q0fXHXC5/V9a0MDIIziVKZvFJEv/UxI3ToD8zdlYHCiup85Wd2MqhTMMQYc9Gh9pJSDdCtTUEpR/h3h95nNfJz5tiz0Zw2bsXP7uE/yOLrYvezG4teiB6/GTGIPBweLtS2G2kHL6Tb1+WIvDjIOKaNTGB4y2DBBQec2xNluYh0vtvn45bYdUxDxxwKzlATVum2BjGcfA1g+3w/QDBy4sdPHUFg3HL5lcdfRyJ90mwE2/qCrZuknwD5e/JU3nvNvzEW0YR3qGBsTUZrA5MnKdfExYuE6IpDmJek8gfA8eKA0aYkOq22JFVqAaZ52pK03G8j6FjhRkB/XDAUDHeXOAEY1WbTNhX2kyhMlO6RkYI1H4uuNRxtE7Ul/ceF/fIbCD1OElMWRCoGa1bppWyqkDtBdb6O40tcxAbuJZa9fZe/UsWtRH9tUAtkjJIEjiAMGJPlFv5a5FyYB00rJgibbug=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
